### PR TITLE
Support all three discovery methods, fixes #3

### LINKED ISSUE #3: Box discovery
We need to work out how the client discovers the Box.

Terminology:
Box: The box being developed in Project Link
QR: Use a QR-code on a sticker on the Box to tell the client which URL connect to
mDNS: The Box uses mDNS to tell the client its IP address and/or its full URL
HSS: The client checks the TLS certificate against the fingerprint in the trusted URL string
plex: A public DNS zone is used to announce the Box's local IP address
LE: LetsEncrypt is used to register/renew a TLS certificate for the public plex-like domain name
NUPNP: A server on which the Box can publish its local IP address so that the client can discover it
Cordova: A tool for packaging web apps a native apps, with plugins for adding custom functionality that is usually not available in browsers.
client: A smartphone, tablet, laptop, or TV.

Assumptions:
- QR-codes work well on smartphones and tablets, but not on laptops and TVs
- mDNS is supported by major browsers on iOS, OSX and Linux, but not (yet) on Android and Windows
- we prefer a secure solution
- we prefer a local solution (not leaking user data to the cloud)
- we prefer a solution that uses standard mobile browsers (and standard mobile QR-code readers)

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by arcturus** [comment]
I would love to go with this solution, at run time if possible :)

**Comment by michielbdejong** [comment]
Right, the box could have a physical switch which you can put in "Secure", "Default" or "Easy" mode before plugging it in for the first time.

**Comment by michielbdejong** [comment]
So basically:

```
option:   name discovery:     establishing IP connection:        security:
==================================================================================
secure    QR code             mDNS                               fingerprint check
medium    QR code             local IP addr in a public DNS      LetsEncrypt
easy      nupnp               local IP addr in a public DNS      LetsEncrypt
```

**Comment by michielbdejong** [comment]
Also, there will eventually be a need for connecting an additional client while not in the house.

Pairing the first admin client can only be done while in the same building (based on either scanning the QR code or in the case of nupnp, the public IP address assigned by the ISP). This is reasonable, because when you just switch on the Box for the first time, you are by definition in the same building as the Box.

Clients that are on the same wifi network as the Box can send it an access request, to be approved by the admin.

Clients that are not, cannot send such access requests out of the blue, because either they have no way to obtain the long name of the Box, or if using a short name (memorable-username.knilxof-remote.org), it would be too tempting for an attacker to flood Box admins with hundreds of access requests.

Therefore we need some sort of PIN / One-Time-Password flow, where the user generates a short code on an already paired client, and types that into the new client they want to pair (or similar).

**Comment by michielbdejong** [comment]
Apart from the flow that uses the registration-server (which is already implemented), let's just implement mDNS+TOFU, as described in https://github.com/fxbox/RFC/pull/4#issuecomment-198333564.

I'll publish my work on "securely connected devices" on my personal blog instead, and give up on pushing QR-codes within Project Link. I think some people in the project will be happy to hear that. ;)

**Comment by michielbdejong** [comment]
Retracting this proposal in favor of https://github.com/fxbox/RFC/pull/12.

**Pull request closed without merging**
