### PR TITLE
Wrapping cargo with mach, the command dispatcher

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Links to:
- https://github.com/fxbox/foxbox/issues/516
- https://github.com/fxbox/foxbox/issues/449
- https://github.com/fxbox/foxbox/issues/157
- https://github.com/fxbox/foxbox/pull/440

r? @fabricedesre @julienw @samgiles @jedireza + anyone interested

### CODE REVIEW

**Comment by fabricedesre** [comment]
I think we'll have to do it - likely copying as much as we can from servo. They even install the right rustc version locally to have something very self contained.

**Comment by samgiles** [comment]
I'm in favour of this generally. I haven't looked at Servo for a while - how much could we reuse/share, or has it ended up being very specific to Servo?

**Comment by julienw** [comment]
I'd favor using the mach from servo as well (I haven't looked much closer). I don't like the idea of doing our own stuff. It was ok while run.sh was only 1 line but if we need more than this, let's use something existing.

But let's try to not depend on it too much, as maybe cargo will eventually evolve to support some of our issues. It's ok to depend on it to launch commands before/after building/testing, but for example I'm not so at ease with the idea of installing dependencies. (although I wouldn't block this)

**Comment by JohanLorenzo** [comment]
There hasn't been any activity on this PR for more than 2 years. Although, I see some fxbox repos still have some activity. I'm closing this PR for the sake of cleanup. Please reopen if you think it still has some use.

**Pull request closed without merging**
